### ISSUE TITLE
Error when I run Work Histories

### ISSUE THREAD

**Issue by pmed993** [ljwright/work-life-histories-ukhls-bhps#3]
Dear Liam,

First of all thanks for such a beautiful project, I think is great and for sure will make my research easier.

While the first two parts of the program run smoothly (Prepare basis data and Education data), I have encountered an error when I am running the Work Histories part and I was not able to continue with the data extraction.

Find attach a picture of the error (let me know if you may need further information)

![Screenshot 2021-11-09 at 18 36 19](https://user-images.githubusercontent.com/68660313/140987060-a9944d3f-6556-44c6-86fd-5a10bbd4a714.png)
:

The same error occurs for the BHPS Annual History- Wave 1-15.do and 
BHPS Annual History - Wave 16-18.do

Do you have some thought on what might cause the error?

Thanks

**Comment by ljwright** [comment]
Hi Pio,

Thanks for this. I'm glad you are (potentially!) finding the code useful.

Would you be able to remove the `qui` bit of each line. `qui` is short for `quietly` and runs the code supressing the output. If you remove `qui`, I'll be able to see exactly where the error occurs.

Thanks,

Liam

**Comment by pmed993** [comment]
Thanks for your reply, find attached a picture of the error after removing `qui`

![Working Histories error](https://user-images.githubusercontent.com/68660313/141374581-e7179174-0149-40be-9e92-def732506af3.png)
:

The error happens in the Clean Work History.do part 8, let me know if you may need something else. Unfortunately I can not run a log file as I have a problem with my Stata at the moment.

**Comment by ljwright** [comment]
Hmm that's interesting. What version of Stata are you using? Usually `drop` should return a value with how many observations are dropped (into `r(N_drop)`), but it doesn't seem to have done.

**Comment by ljwright** [comment]
Having looked through the manuals (https://www.stata.com/manuals13/ddrop.pdf, https://www.stata.com/manuals14/ddrop.pdf, etc.), it seems Version 15 and above will be needed to run the code as it currently stands.

The alternative is to change
```
drop if Start_MY > End_MY 
if `r(N_drop)' == 0{ 
    continue, break
}
```
To
```
count if Start_MY > End_MY
local to_drop = `r(N)'
drop if Start_MY > End_MY 
if `to_drop' == 0{ 
    continue, break
}
```

That said, I can't guarantee there won't be other commands somewhere in the code that have issues with earlier versions of Stata.

**Comment by pmed993** [comment]
I am currently using STATA 14, after changing the code the program run smoothly, thanks for your help!

**Comment by ljwright** [comment]
Great. Glad it works and thanks for letting me know.

I've updated the code on here to reflect the issue you found.
